### ISSUE TITLE
Not sure if it's because of this loop...

### ISSUE THREAD

**Issue by VincentKempers** [IIYAMA12/wafs#4]
I'm not sure it's here but ... close to the end it skips some content. Maybe you don't want to show it on the end result (or maybe you do) it skips a lot. If there is a asteroid that zooms by maybe show the line either way just to show it's there? 

I'm super interested on the how and where those were.

https://github.com/IIYAMA12/wafs/blob/19e9b719550ddbb2dcc13692731d19e695e6408e/app/static/scripts/index.js#L202

**Comment by IIYAMA12** [comment]
fixed
